### ISSUE TITLE
[Feature Request] ROSify pose output

### ISSUE THREAD

**Issue by diegomrt** [JdeRobot/SDslam#15]
Hi again, 

It seems that in the present ROS version of the algorithm, the nodes get data from ROS topics, but the output is not  published as a ROS topic using the standard [geometry_msgs/Pose](http://docs.ros.org/lunar/api/geometry_msgs/html/msg/Pose.html) message.

It would be nice to have the pose ROSified, to allow communication with other ROS nodes. 

Thanx.

**Comment by javimdr** [comment]
Hi,

I have made an improvement in which I have implemented the characteristic that you requested.

The position of the camera is published as a transformation (tf) and as a [geometry_msgs/PoseStamped](http://docs.ros.org/lunar/api/geometry_msgs/html/msg/PoseStamped.html) message (which contains the [geometry_msgs/Pose](http://docs.ros.org/lunar/api/geometry_msgs/html/msg/Pose.html) information) which is published in "sdslam/pose", even though it can be modified from the YAML file.

I think it works properly, as it can be observed in the following [video](https://youtu.be/AcKQcqukvYM).

**Comment by eperdices** [comment]
I have just accepted the pull request implementing this feature.
